export const CONFIG = {
	BASE_SPEED: 6,
	BASE_HEALTH: 6,
	HEALTH_BODY_MULTIPIER: 3,
	MAX_LUCK: 5,
	BASE_EVASION: 4,
	PJ_POWER_SPENT_PP_DIVIDER: 10,
	STARTING_LUCK: 2,
	BASE_MAX_ACTIVE_CARDS: 3,
	RELOAD_CARD_USES: 1,

	MOBILE_MAX_WIDTH: 1024,
};
